name: Website

on:
  push:
    branches:
      - master
      - docs2
    tags:
      - docs.*

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout all branches
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11
      - run: |
          ./scripts/createSite.sh ${{ github.ref }}
      - name: Release to GitHub Pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: ./website/build/zio-connect
